=== consultant-1379/security-poc/credential-manager-service/credential-manager-service-entity-xmlbeans/src/main/resources/EntitiesSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="PKIEntities" type="PKIEntities" />


    <xs:complexType name="PKIEntities">
        <xs:sequence>
            <xs:element name="Entities" type="Entities" minOccurs="0">
                <xs:unique name="UniqueEndEntitynames">
                    <xs:selector xpath="Entity"></xs:selector>
                    <xs:field xpath="@Name"></xs:field>
                    <xs:field xpath="EntityProfileName"></xs:field>
                </xs:unique>
            </xs:element>
            <xs:element name="CA-Entities" type="CAEntities" minOccurs="0">
                <xs:unique name="UniqueCAEntitynames">
                    <xs:selector xpath="CAEntity"></xs:selector>
                    <xs:field xpath="@Name"></xs:field>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Entities">
        <xs:sequence>
            <xs:element name="Entity" type="Entity" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="CAEntities">
        <xs:sequence>
            <xs:element name="CAEntity" type="CAEntity" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AbstractEntity" abstract="true">
        <xs:sequence>
            <xs:element name="Subject" type="Subject" minOccurs="0" />
            <xs:element name="SubjectAltNameValues" type="SubjectAltNameValues" minOccurs="0" />
            <xs:element name="EntityProfileName" type="nonEmptyString" />
            <xs:element name="KeyGenerationAlgorithm" type="Algorithm" minOccurs="0" />
            <xs:element name="PublishCertificatetoTDPS" type="xs:boolean" minOccurs="0" />
            <xs:element name="IssuerDN" type="Subject" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="Name" type="nonEmptyString" use="required" />
    </xs:complexType>

    <xs:complexType name="CAEntity">
        <xs:complexContent>
            <xs:extension base="AbstractEntity">
                <xs:sequence>
                    <xs:element name="RootCA" type="xs:boolean" minOccurs="1" />
                    <xs:element name="CACRL" type="CACRL" minOccurs="0" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="CACRL">
        <xs:sequence> 
			<xs:element name="PublishCRLToCDPS" type="xs:boolean" />
			<xs:element name="CRLGenerationInfo" type="CRLGenerationInfo" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>	
 
    <xs:complexType name="CRLGenerationInfo">
        <xs:sequence>
			<xs:element name="Version" 				type="nonEmptyString" />
			<xs:element name="SignatureAlgorithm" 	    type="Algorithm" />
			<xs:element name="ValidityPeriod"			type="xs:duration" /> 
 			<xs:element name="SkewCrlTime" 				type="xs:duration" /> 
			<xs:element name="OverlapPeriod" 			type="xs:duration" /> 
			<xs:element name="CrlExtensions"    		type="CrlExtensions" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
 
    <xs:complexType name="CrlExtensions">
		<xs:sequence>
			<xs:element name="CRLNumber" type="CRLNumber" minOccurs="0" />
			<xs:element name="AuthorityInformationAccess" type="AuthorityInformationAccess"
				minOccurs="0" />
			<xs:element name="AuthorityKeyIdentifier" type="AuthorityKeyIdentifier"
				minOccurs="0" />
			<xs:element name="IssuingDistributionPoint" type="IssuingDistributionPoint"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType> 

	<xs:complexType name="CRLExtension" abstract="true">
		<xs:sequence>
			<xs:element name="Critical" type="xs:boolean" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="AuthorityKeyIdentifier">
		<xs:complexContent>
			<xs:extension base="CRLExtension">
				<xs:choice>
					<xs:element name="ByKeyIdentifier" type="xs:boolean" />
					<xs:element name="ByAuthorityCertIssuerAndSerialNumber"
						type="xs:boolean" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="CRLNumber">
		<xs:sequence>
			<xs:element name="Critical" type="xs:boolean" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AuthorityInformationAccess">
		<xs:complexContent>
			<xs:extension base="CRLExtension">
				<xs:sequence>
					<xs:element name="AccessDescription" type="AccessDescription"
						minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AccessDescription">
		<xs:sequence>
			<xs:element name="AccessMethod" type="AccessMethod"
				minOccurs="0" />
			<xs:element name="AccessLocation" type="nonEmptyString"
				nillable="true" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="AccessMethod">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CA_ISSUER" />
			<xs:enumeration value="OCSP" />
		</xs:restriction>
	</xs:simpleType>
	
	
	<xs:complexType name="IssuingDistributionPoint">
		<xs:complexContent>
			<xs:extension base="CRLExtension">	
				<xs:sequence>
					<xs:element name="OnlyContainsUserCerts" type="xs:boolean"
				minOccurs="0" />
					<xs:element name="OnlyContainsCACerts" type="xs:boolean"
				minOccurs="0" />
					<xs:element name="IndirectCRL" type="xs:boolean"
				minOccurs="0" />
					<xs:element name="OnlyContainsAttributeCerts" type="xs:boolean"
				minOccurs="0" />
					<xs:element name="DistributionPoint" type="DistributionPointName" minOccurs="0" />	
					<xs:element name="ReasonFlag" type="ReasonFlag" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:simpleType name="ReasonFlag">
		<xs:restriction base="xs:string">
			<xs:enumeration value="UNUSED" />
			<xs:enumeration value="KEY_COMPROMISE" />
			<xs:enumeration value="CA_COMPROMISE" />
			<xs:enumeration value="AFFILIATION_CHANGED" />
			<xs:enumeration value="SUPERSEDED" />
			<xs:enumeration value="CESSATION_OF_OPERATION" />
			<xs:enumeration value="CERTIFICATE_HOLD" />
			<xs:enumeration value="PRIVILEGE_WITHDRAWN" />
			<xs:enumeration value="AA_COMPROMISE" />
		</xs:restriction>
	</xs:simpleType>	
	
	<xs:complexType name="DistributionPointName">
		<xs:choice>
			<xs:element name="FullName" type="nonEmptyString"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="NameRelativeToCRLIssuer" type="nonEmptyString"
				minOccurs="0" />
		</xs:choice>
	</xs:complexType>	
	
    <xs:complexType name="Entity">
        <xs:complexContent>
            <xs:extension base="AbstractEntity">
                <xs:sequence>
                 <xs:element name="OTP" type="nonEmptyString" minOccurs="0" />
                 </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

   <xs:complexType name="SubjectAltNameValues">
		<xs:sequence>
			<xs:element name="SubjectAltNameValue" type="SubjectAltNameValue"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SubjectAltNameValue">
		<xs:sequence>
			<xs:element name="Type" type="SubjectAltNameFieldType" />
			<xs:element name="Value" type="AbstractSubjectAltNameValueType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AbstractSubjectAltNameValueType" abstract="true">
		<xs:sequence />
	</xs:complexType>

	<xs:complexType name="OtherName">
		<xs:complexContent>
			<xs:extension base="AbstractSubjectAltNameValueType">
				<xs:sequence>
					<xs:element name="TypeId" type="nonEmptyString" />
					<xs:element name="Value" type="nonEmptyString" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="EdiPartyName">
		<xs:complexContent>
			<xs:extension base="AbstractSubjectAltNameValueType">
				<xs:sequence>
					<xs:element name="NameAssigner" type="nonEmptyString" />
					<xs:element name="PartyName" type="nonEmptyString" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SubjectAltNameString">
		<xs:complexContent>
			<xs:extension base="AbstractSubjectAltNameValueType">
				<xs:sequence>
					<xs:element name="StringValue" type="nonEmptyString"
						minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

    <xs:complexType name="Algorithm">
        <xs:sequence>
            <xs:element name="Name" type="nonEmptyString" />
            <xs:element name="KeySize" type="xs:positiveInteger" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Subject">
        <xs:sequence>
            <xs:element name="SubjectDN" type="SubjectMapModeller" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SubjectMapModeller">
        <xs:sequence>
            <xs:element name="SubjectEntry" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Type" type="SubjectFieldType" />
                        <xs:element name="Value" type="nonEmptyString" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="SubjectFieldType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="COMMON_NAME" />
            <xs:enumeration value="SURNAME" />
            <xs:enumeration value="COUNTRY_NAME" />
            <xs:enumeration value="LOCALITY_NAME" />
            <xs:enumeration value="STATE" />   
		    <xs:enumeration value="STREET_ADDRESS" />
            <xs:enumeration value="ORGANIZATION" />
            <xs:enumeration value="ORGANIZATION_UNIT" />
            <xs:enumeration value="DN_QUALIFIER" />
            <xs:enumeration value="TITLE" />
            <xs:enumeration value="GIVEN_NAME" />
            <xs:enumeration value="SERIAL_NUMBER" />
        </xs:restriction>
    </xs:simpleType>



    <xs:simpleType name="SubjectAltNameFieldType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RFC822_NAME" />
            <xs:enumeration value="OTHER_NAME" />
            <xs:enumeration value="EDI_PARTY_NAME" />
            <xs:enumeration value="DNS_NAME" />
            <xs:enumeration value="X400_ADDRESS" />
            <xs:enumeration value="DIRECTORY_NAME" />
            <xs:enumeration value="UNIFORM_RESOURCE_IDENTIFIER" />
            <xs:enumeration value="IP_ADDRESS" />
            <xs:enumeration value="REGESTERED_ID" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== consultant-1379/security-poc/pki-web-cli/pki-web-cli-jar/src/test/resources/CEntities.xml
<?xml version="1.0" encoding="UTF-8"?>
<PKIEntities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="EntitiesSchema.xsd">
	<CA-Entities>
        <CAEntity Name="RootCA_7">
            <Subject>
                <SubjectDN>
                    <SubjectEntry>
                        <Type>COMMON_NAME</Type>
                        <Value> ARJ_Root </Value>
                    </SubjectEntry>
                </SubjectDN>
            </Subject>
            <EntityProfileName>RootCA_Entity_Profile</EntityProfileName>
            <RootCA>true</RootCA>
            <CACRL>
                <CRLGenerationPeriod>P21D</CRLGenerationPeriod>
                <CRLSignatureAlgorithm>
                    <Name>RSA</Name>
                    <KeySize>1024</KeySize>
                </CRLSignatureAlgorithm>
                <PublishCRLToCDPS>true</PublishCRLToCDPS>
            </CACRL>
        </CAEntity>
    </CA-Entities>
</PKIEntities>

=== consultant-1379/security-poc/credential-manager-service/credential-manager-service-jar/src/test/resources/caEntityCRLGen.xml
<?xml version="1.0" encoding="UTF-8"?>
<PKIEntities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="EntitiesSchema.xsd">
	<CA-Entities>


		<!-- Same CA in caEntities.xml with CRLGenerationInfo to trigger update code section -->
		<CAEntity Name="ENM_PKI_CRLGenINFOTest_CA">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>RootCA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<SubjectAltNameValues>
				
				<SubjectAltNameValue>
						<Type>IP_ADDRESS</Type>
						<Value xsi:type="SubjectAltNameString">
							<StringValue>1.1.1.2</StringValue>
						</Value>
				</SubjectAltNameValue>
			
			</SubjectAltNameValues>
			
			<EntityProfileName>entityProfile</EntityProfileName>
			
			<KeyGenerationAlgorithm>
				<Name>RSA</Name>
				<KeySize>2048</KeySize>
			</KeyGenerationAlgorithm>
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
			<RootCA>true</RootCA>
				
			<CACRL>
				<PublishCRLToCDPS>true</PublishCRLToCDPS>
			</CACRL>
		</CAEntity>

	</CA-Entities>
</PKIEntities>

=== consultant-1379/security-poc/pki-web-cli/pki-web-cli-jar/src/test/resources/EEntities.xml
<?xml version="1.0" encoding="UTF-8"?>
<PKIEntities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="EntitiesSchema.xsd">
	<Entities>
		<Entity Name="Entity_5">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>Entity_1</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			<SubjectAltNameValues>
				<SubjectAltNameValue>
					<Type>EDI_PARTY_NAME</Type>
					<Value xsi:type="EdiPartyName">
						<NameAssigner>TCS</NameAssigner>
						<PartyName>adksl</PartyName>
					</Value>
				</SubjectAltNameValue>
			</SubjectAltNameValues>

			<EntityProfileName>RootCA_Entity_Profile</EntityProfileName>
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
		</Entity>
		<Entity Name="Entity_6">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>Entity_1</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			<EntityProfileName>RootCA_Entity_Profile</EntityProfileName>
		</Entity>
	</Entities>
</PKIEntities>

=== consultant-1379/security-poc/pki-web-cli/pki-web-cli-jar/src/test/resources/entities.xml
<Entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="EntitiesSchema.xsd">
<CAEntity>	
	<EntityProfileName>RootCA_Entity_Profile</EntityProfileName>
		<KeyGenerationAlgorithm>
			<Name>DES</Name>
			<KeySize>1024</KeySize>
		</KeyGenerationAlgorithm>
		<CertificateAuthority>
		<Name>RootCA_127</Name>
		<IsRootCA>true</IsRootCA>
		<SubjectIdentifier>
		<Subject>
			<SubjectDN>
				<SubjectEntry>
					<Type>COMMON_NAME</Type>
					<Value> ARJ_Root </Value>
				</SubjectEntry>
			</SubjectDN>
		</Subject>
		<SubjectAltNameValues>
			<SubjectAltNameValue>
				<Type>DIRECTORY_NAME</Type>
				<Value xsi:type="SubjectAltNameString">
					<StringValue>www.xyz.com (http://www.xyz.com)</StringValue>
				</Value>
			</SubjectAltNameValue>
		</SubjectAltNameValues>
		</SubjectIdentifier>
		<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
		</CertificateAuthority>
	</CAEntity> 
	<Entity >	
	<EntityProfileName>RootCA_Entity_Profile</EntityProfileName>
		<KeyGenerationAlgorithm>
			<Name>DES</Name>
			<KeySize>2048</KeySize>
		</KeyGenerationAlgorithm>
		<EntityInfo>
				<Name>ERBS_13</Name>
				<SubjectIdentifier>
						<Subject>
							<SubjectDN>
								<SubjectEntry>
									<Type>COMMON_NAME</Type>
									<Value>Entity_ERBS_1</Value>
								</SubjectEntry>
							</SubjectDN>
						</Subject>
						<SubjectAltNameValues>
							<SubjectAltNameValue>
								<Type>EDI_PARTY_NAME</Type>
								<Value xsi:type="EdiPartyName">
									<NameAssigner>TCS</NameAssigner>
									<PartyName>adksl</PartyName>
								</Value>
							</SubjectAltNameValue>
						</SubjectAltNameValues>
				</SubjectIdentifier>
		</EntityInfo>
		<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
		<OTP>2ER13SA32SAD2G3</OTP>
</Entity> 
	</Entities>

=== consultant-1379/security-poc/credential-manager-service/ERICcredentialmanagerservice_CXP9031868/src/main/resources/config/service/data/enmInit/credM/ENM-Root-CA/Entities/ADP-PKI-Root-CA.xml
<?xml version="1.0" encoding="UTF-8"?>
<PKIEntities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="EntitiesSchema.xsd">

	<CA-Entities>
		<CAEntity Name="ADP_PKI_Root_CA">
		
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>ADP_PKI_Root_CA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<EntityProfileName>ADP_PKI_Root_CA_EP</EntityProfileName>
			<KeyGenerationAlgorithm>
				<Name>RSA</Name>
				<KeySize>2048</KeySize>
			</KeyGenerationAlgorithm>
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
			
			<RootCA>true</RootCA>
				
			<CACRL>
				<PublishCRLToCDPS>true</PublishCRLToCDPS>
				<CRLGenerationInfo>
				<Version>V2</Version>
				<SignatureAlgorithm>
					<Name>SHA256withRSA</Name>
					<KeySize>2048</KeySize>
				</SignatureAlgorithm>
				<ValidityPeriod>P30D</ValidityPeriod>
				<SkewCrlTime>PT30M</SkewCrlTime>
				<OverlapPeriod>P1D</OverlapPeriod>
				<CrlExtensions>
					<CRLNumber>
						<Critical>false</Critical>
					</CRLNumber>
					<AuthorityKeyIdentifier>
						<Critical>false</Critical>
						<ByAuthorityCertIssuerAndSerialNumber>true</ByAuthorityCertIssuerAndSerialNumber>
					</AuthorityKeyIdentifier>
				</CrlExtensions>
				</CRLGenerationInfo>		
			</CACRL>
			
		</CAEntity>
	</CA-Entities>
</PKIEntities>

=== consultant-1379/security-poc/credential-manager-service/credential-manager-service-jar/src/test/resources/ENM-PKI-Root-CA.xml
<?xml version="1.0" encoding="UTF-8"?>
<PKIEntities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="EntitiesSchema.xsd">
	<CA-Entities>
		<CAEntity Name="ENM PKI Root CA">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>ENM PKI Root CA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<EntityProfileName>ENM PKI Root CA EP</EntityProfileName>
						
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
			
			<RootCA>true</RootCA>
				
			<CACRL>
				<PublishCRLToCDPS>true</PublishCRLToCDPS>
				<CRLGenerationInfo>
				<Version>V2</Version>
				<SignatureAlgorithm>
					<Name>SHA256withRSA</Name>
					<KeySize>2048</KeySize>
				</SignatureAlgorithm>
				<ValidityPeriod>P30D</ValidityPeriod>
				<SkewCrlTime>PT30M</SkewCrlTime>
				<OverlapPeriod>P1D</OverlapPeriod>
				<CrlExtensions>
					<CRLNumber>
						<Critical>false</Critical>
					</CRLNumber>
					<AuthorityKeyIdentifier>
						<Critical>false</Critical>
						<ByAuthorityCertIssuerAndSerialNumber>true</ByAuthorityCertIssuerAndSerialNumber>
					</AuthorityKeyIdentifier>
				</CrlExtensions>
				</CRLGenerationInfo>
			</CACRL>
		</CAEntity>
	</CA-Entities>
</PKIEntities>

=== consultant-1379/security-poc/credential-manager-service/credential-manager-service-jar/src/test/resources/ENM-Sub1-CA/Entities/ENM-Sub1-CA.xml
<?xml version="1.0" encoding="UTF-8"?>
<PKIEntities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="EntitiesSchema.xsd">
	<CA-Entities>
	
		<CAEntity Name="NE External CA">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>NE External CA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<EntityProfileName>NE CA EP</EntityProfileName>
						
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
			
			<RootCA>false</RootCA>
				
				<CACRL>
				<PublishCRLToCDPS>true</PublishCRLToCDPS>
				<CRLGenerationInfo>
				<Version>V2</Version>
				<SignatureAlgorithm>
					<Name>SHA256withRSA</Name>
					<KeySize>2048</KeySize>
				</SignatureAlgorithm>
				<ValidityPeriod>P15D</ValidityPeriod>
				<SkewCrlTime>PT30M</SkewCrlTime>
				<OverlapPeriod>P1D</OverlapPeriod>
				<CrlExtensions>
					<CRLNumber>
						<Critical>false</Critical>
					</CRLNumber>
					<AuthorityKeyIdentifier>
						<Critical>false</Critical>
						<ByAuthorityCertIssuerAndSerialNumber>true</ByAuthorityCertIssuerAndSerialNumber>
					</AuthorityKeyIdentifier>
				</CrlExtensions>
				</CRLGenerationInfo>
			</CACRL>
		</CAEntity>
		<CAEntity Name="NE IPsec CA">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>NE IPsec CA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<EntityProfileName>NE CA EP</EntityProfileName>
						
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
			
			<RootCA>false</RootCA>
				
				<CACRL>
				<PublishCRLToCDPS>true</PublishCRLToCDPS>
				<CRLGenerationInfo>
				<Version>V2</Version>
				<SignatureAlgorithm>
					<Name>SHA256withRSA</Name>
					<KeySize>2048</KeySize>
				</SignatureAlgorithm>
				<ValidityPeriod>P15D</ValidityPeriod>
				<SkewCrlTime>P30M</SkewCrlTime>
				<OverlapPeriod>P1D</OverlapPeriod>
				<CrlExtensions>
					<CRLNumber>
						<Critical>false</Critical>
					</CRLNumber>
					<AuthorityKeyIdentifier>
						<Critical>false</Critical>
						<ByAuthorityCertIssuerAndSerialNumber>true</ByAuthorityCertIssuerAndSerialNumber>
					</AuthorityKeyIdentifier>
				</CrlExtensions>
				</CRLGenerationInfo>
			</CACRL>
		</CAEntity>		
		<CAEntity Name="NE OAM CA">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>NE OAM CA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<EntityProfileName>NE CA EP</EntityProfileName>
						
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
			
			<RootCA>false</RootCA>
				
			<CACRL>
				<PublishCRLToCDPS>true</PublishCRLToCDPS>
				<CRLGenerationInfo>
				<Version>V2</Version>
				<SignatureAlgorithm>
					<Name>SHA256withRSA</Name>
					<KeySize>2048</KeySize>
				</SignatureAlgorithm>
				<ValidityPeriod>P15D</ValidityPeriod>
				<SkewCrlTime>P30M</SkewCrlTime>
				<OverlapPeriod>P1D</OverlapPeriod>
				<CrlExtensions>
					<CRLNumber>
						<Critical>false</Critical>
					</CRLNumber>
					<AuthorityKeyIdentifier>
						<Critical>false</Critical>
						<ByAuthorityCertIssuerAndSerialNumber>true</ByAuthorityCertIssuerAndSerialNumber>
					</AuthorityKeyIdentifier>
				</CrlExtensions>
				</CRLGenerationInfo>
			</CACRL>
		</CAEntity>				

		<CAEntity Name="ENM Infrastructure CA">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>ENM Infrastructure CA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<EntityProfileName>ENM CA EP</EntityProfileName>
						
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
			
			<RootCA>false</RootCA>
				
						<CACRL>
				<PublishCRLToCDPS>true</PublishCRLToCDPS>
				<CRLGenerationInfo>
				<Version>V2</Version>
				<SignatureAlgorithm>
					<Name>SHA256withRSA</Name>
					<KeySize>2048</KeySize>
				</SignatureAlgorithm>
				<ValidityPeriod>P15D</ValidityPeriod>
				<SkewCrlTime>P30M</SkewCrlTime>
				<OverlapPeriod>P1D</OverlapPeriod>
				<CrlExtensions>
					<CRLNumber>
						<Critical>false</Critical>
					</CRLNumber>
					<AuthorityKeyIdentifier>
						<Critical>false</Critical>
						<ByAuthorityCertIssuerAndSerialNumber>true</ByAuthorityCertIssuerAndSerialNumber>
					</AuthorityKeyIdentifier>
				</CrlExtensions>
				</CRLGenerationInfo>
			</CACRL>
		</CAEntity>				
		<CAEntity Name="ENM E-mail CA">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>ENM E-mail CA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<EntityProfileName>ENM CA EP</EntityProfileName>
						
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
			
			<RootCA>false</RootCA>
				
					<CACRL>
				<PublishCRLToCDPS>true</PublishCRLToCDPS>
				<CRLGenerationInfo>
				<Version>V2</Version>
				<SignatureAlgorithm>
					<Name>SHA256withRSA</Name>
					<KeySize>2048</KeySize>
				</SignatureAlgorithm>
				<ValidityPeriod>P15D</ValidityPeriod>
				<SkewCrlTime>P30M</SkewCrlTime>
				<OverlapPeriod>P1D</OverlapPeriod>
				<CrlExtensions>
					<CRLNumber>
						<Critical>false</Critical>
					</CRLNumber>
					<AuthorityKeyIdentifier>
						<Critical>false</Critical>
						<ByAuthorityCertIssuerAndSerialNumber>true</ByAuthorityCertIssuerAndSerialNumber>
					</AuthorityKeyIdentifier>
				</CrlExtensions>
				</CRLGenerationInfo>
			</CACRL>
		</CAEntity>				
		<CAEntity Name="ENM External Entity CA">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>ENM External Entity CA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<EntityProfileName>ENM CA EP</EntityProfileName>
						
			<PublishCertificatetoTDPS>true</PublishCertificatetoTDPS>
			
			<RootCA>false</RootCA>
				
			<CACRL>
				<PublishCRLToCDPS>true</PublishCRLToCDPS>
				<CRLGenerationInfo>
				<Version>V2</Version>
				<SignatureAlgorithm>
					<Name>SHA256withRSA</Name>
					<KeySize>2048</KeySize>
				</SignatureAlgorithm>
				<ValidityPeriod>P15D</ValidityPeriod>
				<SkewCrlTime>P30M</SkewCrlTime>
				<OverlapPeriod>P1D</OverlapPeriod>
				<CrlExtensions>
					<CRLNumber>
						<Critical>false</Critical>
					</CRLNumber>
					<AuthorityKeyIdentifier>
						<Critical>false</Critical>
						<ByAuthorityCertIssuerAndSerialNumber>true</ByAuthorityCertIssuerAndSerialNumber>
					</AuthorityKeyIdentifier>
				</CrlExtensions>			
				</CRLGenerationInfo>
			</CACRL>
		</CAEntity>						
		
	</CA-Entities>
	
</PKIEntities>

=== consultant-1379/security-poc/credential-manager-service/credential-manager-service-jar/src/test/resources/wrongEntities.xml
<?xml version="1.0" encoding="UTF-8"?>
<PKIEntities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="EntitiesSchema.xsd">
	<Entities>
		<Entity Name="WrongEntity">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>WrongEntity</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			
			<SubjectAltNameValues>
				
				<SubjectAltNameValue>
					<Type>IP_ADDRESS</Type>
					<Value xsi:type="SubjectAltNameString">
						<StringValue>1.1.1.1</StringValue>
					</Value>
				</SubjectAltNameValue>					
			
				<SubjectAltNameValue>
					<Type>RFC822_NAME</Type>
					<Value xsi:type="SubjectAltNameString">
						<StringValue>Subjectrfc822</StringValue>
					</Value>
				</SubjectAltNameValue>

				<SubjectAltNameValue>
						<Type>OTHER_NAME</Type>
						<Value xsi:type="OtherName">
							<TypeId>1.6.5.1.8</TypeId>
							<Value>value</Value>
						</Value>
				</SubjectAltNameValue>

				<SubjectAltNameValue>
						<Type>EDI_PARTY_NAME</Type>
						<Value xsi:type="EdiPartyName">
							<NameAssigner>nameAssigner</NameAssigner>
							<PartyName>partyName</PartyName>
						</Value>
				</SubjectAltNameValue>
				
			</SubjectAltNameValues>

			<EntityProfileName>NotExistentProfile</EntityProfileName>

			<KeyGenerationAlgorithm>
				<Name>RSA</Name>
				<KeySize>2048</KeySize>
			</KeyGenerationAlgorithm>

			<OTP>changeit</OTP>
			
		</Entity>
	</Entities>
</PKIEntities>
