=== consultant-1379/security-poc/credential-manager-service/credential-manager-service-xmlbeans/src/main/resources/ProfilesSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Profiles" type="Profiles" />

	<xs:complexType name="Profiles">
		<xs:sequence>
			<xs:element name="Trust-Profiles" type="TrustProfiles"
				minOccurs="0">
				<xs:unique name="UniqueTrustProfilenames">
					<xs:selector xpath="TrustProfile"></xs:selector>
					<xs:field xpath="@Name"></xs:field>
				</xs:unique>
			</xs:element>

			<xs:element name="Certificate-Profiles" type="CertificateProfiles"
				minOccurs="0">
				<xs:unique name="UniqueCertificateProfilenames">
					<xs:selector xpath="CertificateProfile"></xs:selector>
					<xs:field xpath="@Name"></xs:field>
				</xs:unique>
			</xs:element>

			<xs:element name="Entity-Profiles" type="EntityProfiles"
				minOccurs="0">
				<xs:unique name="UniqueEntityProfilenames">
					<xs:selector xpath="EntityProfile"></xs:selector>
					<xs:field xpath="@Name"></xs:field>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TrustProfiles">
		<xs:sequence>
			<xs:element name="TrustProfile" type="TrustProfile"
				minOccurs="1" maxOccurs="unbounded">
				<xs:unique name="uniqueInternalCAs">
					<xs:selector xpath="InternalCA"></xs:selector>
					<xs:field xpath="."></xs:field>
				</xs:unique>
				<xs:unique name="UniqueExternalCAs">
					<xs:selector xpath="ExternalCA"></xs:selector>
					<xs:field xpath="."></xs:field>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="CertificateProfiles">
		<xs:sequence>
			<xs:element name="CertificateProfile" type="CertificateProfile"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="EntityProfiles">
		<xs:sequence>
			<xs:element name="EntityProfile" type="EntityProfile"
				minOccurs="1" maxOccurs="unbounded">
				<xs:unique name="UniqueTrustProfileNames">
					<xs:selector xpath="TrustProfileName"></xs:selector>
					<xs:field xpath="."></xs:field>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AbstractProfile" abstract="true">
		<xs:sequence />
		<xs:attribute name="Name" type="nonEmptyString" use="required" />
	</xs:complexType>


	<xs:complexType name="TrustProfile">
		<xs:complexContent>
			<xs:extension base="AbstractProfile">
				<xs:sequence>
					<xs:element name="InternalCA" type="nonEmptyString"
						nillable="true" minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="ExternalCA" type="nonEmptyString"
						nillable="true" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>



	<xs:complexType name="CertificateProfile">
		<xs:complexContent>
			<xs:extension base="AbstractProfile">
				<xs:sequence>
					<xs:element name="SubjectCapabilities" type="Subject"
						minOccurs="0" />
					<xs:element name="IsCAEntity" type="xs:boolean" />
					<xs:element name="Version" type="CertificateVersion" />
					<xs:element name="SignatureAlgorithm" type="Algorithm" />
					<xs:element name="KeyGenerationAlgorithm" type="Algorithm"
						maxOccurs="unbounded" />
					<xs:element name="Validity" type="xs:duration" />
					<xs:element name="Issuer" type="nonEmptyString"
						minOccurs="0" />
					<xs:element name="SubjectUniqueIdentifier" type="xs:boolean"
						minOccurs="0" />
					<xs:element name="IssuerUniqueIdentifier" type="xs:boolean"
						minOccurs="0" />
					<xs:element name="SkewCertificateTime" type="xs:duration"
						minOccurs="0" />
					<xs:element name="CertificateExtensions" type="CertificateExtensions"
						minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="CertificateExtensions">
		<xs:sequence>
			<xs:element name="CertificateExtension" type="CertificateExtension"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Algorithm">
		<xs:sequence>
			<xs:element name="Name" type="nonEmptyString" />
			<xs:element name="KeySize" type="xs:positiveInteger" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Subject">
		<xs:sequence>
			<xs:element name="SubjectDN" type="SubjectMapModeller" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SubjectMapModeller">
		<xs:sequence>
			<xs:element name="SubjectEntry" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Type" type="SubjectFieldType" />
						<xs:element name="Value" type="nonEmptyString" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="CertificateExtension" abstract="true">
		<xs:sequence>
			<xs:element name="Critical" type="xs:boolean" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="BasicConstraints">
		<xs:complexContent>
			<xs:extension base="CertificateExtension">
				<xs:sequence>
					<xs:element name="CA" type="xs:boolean" />
					<xs:element name="PathLenConstraint" type="xs:positiveInteger"
						minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AuthorityInformationAccess">
		<xs:complexContent>
			<xs:extension base="CertificateExtension">
				<xs:sequence>
					<xs:element name="AccessDescription" type="AccessDescription"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AccessDescription">
		<xs:sequence>
			<xs:element name="AccessMethod" type="AccessMethod" />
			<xs:element name="AccessLocation" type="nonEmptyString"
				nillable="true" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AuthorityKeyIdentifier">
		<xs:complexContent>
			<xs:extension base="CertificateExtension">
				<xs:choice>
					<xs:element name="ByKeyIdentifier" type="xs:boolean" />
					<xs:element name="ByAuthorityCertIssuerAndSerialNumber"
						type="xs:boolean" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SubjectKeyIdentifier">
		<xs:complexContent>
			<xs:extension base="CertificateExtension">
				<xs:sequence>
                   <xs:element name="KeyIdentifierAlgorithm" type="nonEmptyString" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="SubjectAltName">
		<xs:complexContent>
			<xs:extension base="CertificateExtension">
				<xs:sequence>
					<xs:element name="SupportedSubjectAltNameField" type="SubjectAltNameFieldType"
						minOccurs="1" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="KeyUsage">
		<xs:complexContent>
			<xs:extension base="CertificateExtension">
				<xs:sequence>
					<xs:element name="KeyUsageType" type="KeyUsageType"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ExtendedKeyUsage">
		<xs:complexContent>
			<xs:extension base="CertificateExtension">
				<xs:sequence>
					<xs:element name="KeyPurposeId" type="KeyPurposeId"
						minOccurs="1" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="CRLDistributionPoints">
		<xs:complexContent>
			<xs:extension base="CertificateExtension">
				<xs:sequence>
					<xs:element name="CRLDistributionPoint" type="CRLDistributionPoint"
						 minOccurs="1" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
    
        <xs:complexType name="CRLDistributionPoint">

        <xs:sequence>
            <xs:element name="DistributionPointName" type="DistributionPointName"
                minOccurs="0" />
            <xs:element name="ReasonFlag" type="ReasonFlag" minOccurs="0" />
            <xs:element name="CRLIssuer" type="nonEmptyString"
                minOccurs="0" />
        </xs:sequence>

    </xs:complexType>

    <xs:complexType name="DistributionPointName">

        <xs:choice>
            <xs:element name="FullName" type="nonEmptyString"
                minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="NameRelativeToCRLIssuer" type="nonEmptyString"
                minOccurs="0" />
        </xs:choice>

    </xs:complexType>
    
    

	<xs:complexType name="EntityProfile">
		<xs:complexContent>
			<xs:extension base="AbstractProfile">
				<xs:sequence>
				 	<xs:element name="Category" type="EntityCategory" minOccurs="0" />
					<xs:element name="Subject" type="Subject" minOccurs="0" />
					<xs:element name="SubjectAltNameValues" type="SubjectAltNameValues"
						minOccurs="0" />
					<xs:element name="KeyGenerationAlgorithm" type="Algorithm"
						minOccurs="0" />
					<xs:element name="CertificateProfileName" type="nonEmptyString" minOccurs="0"/>
					<xs:element name="TrustProfileName" type="nonEmptyString"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="CertificateExtensions" type="CertificateExtensions"
						minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="EntityCategory">
    	<xs:sequence>
     		<xs:element name="Name" type="nonEmptyString" minOccurs="0" default="UNDEFINED" />
    	</xs:sequence>
    </xs:complexType>
	

	<xs:complexType name="SubjectAltNameValues">
		<xs:sequence>
			<xs:element name="SubjectAltNameValue" type="SubjectAltNameValue"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SubjectAltNameValue">
		<xs:sequence>
			<xs:element name="Type" type="SubjectAltNameFieldType" />
			<xs:element name="Value" type="AbstractSubjectAltNameValueType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AbstractSubjectAltNameValueType" abstract="true">
		<xs:sequence />
	</xs:complexType>

	<xs:complexType name="OtherName">
		<xs:complexContent>
			<xs:extension base="AbstractSubjectAltNameValueType">
				<xs:sequence>
					<xs:element name="TypeId" type="nonEmptyString" />
					<xs:element name="Value" type="nonEmptyString" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="EdiPartyName">
		<xs:complexContent>
			<xs:extension base="AbstractSubjectAltNameValueType">
				<xs:sequence>
					<xs:element name="NameAssigner" type="nonEmptyString" />
					<xs:element name="PartyName" type="nonEmptyString" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SubjectAltNameString">
		<xs:complexContent>
			<xs:extension base="AbstractSubjectAltNameValueType">
				<xs:sequence>
					<xs:element name="StringValue" type="nonEmptyString"
						minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>



	<xs:simpleType name="SubjectAltNameFieldType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="RFC822_NAME" />
			<xs:enumeration value="OTHER_NAME" />
			<xs:enumeration value="EDI_PARTY_NAME" />
			<xs:enumeration value="DNS_NAME" />
			<xs:enumeration value="X400_ADDRESS" />
			<xs:enumeration value="DIRECTORY_NAME" />
			<xs:enumeration value="UNIFORM_RESOURCE_IDENTIFIER" />
			<xs:enumeration value="IP_ADDRESS" />
			<xs:enumeration value="REGESTERED_ID" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="CertificateVersion">
		<xs:restriction base="xs:string">
			<xs:enumeration value="V3" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="SubjectFieldType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="COMMON_NAME" />
			<xs:enumeration value="SURNAME" />
			<xs:enumeration value="COUNTRY_NAME" />
			<xs:enumeration value="LOCALITY_NAME" />
			<xs:enumeration value="STATE" />
			<xs:enumeration value="STREET_ADDRESS" />
			<xs:enumeration value="ORGANIZATION" />
			<xs:enumeration value="ORGANIZATION_UNIT" />
			<xs:enumeration value="DN_QUALIFIER" />
			<xs:enumeration value="TITLE" />
			<xs:enumeration value="GIVEN_NAME" />
			<xs:enumeration value="SERIAL_NUMBER" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="AccessMethod">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CA_ISSUER" />
			<xs:enumeration value="OCSP" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="KeyUsageType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DIGITAL_SIGNATURE" />
			<xs:enumeration value="NON_REPUDIATION" />
			<xs:enumeration value="KEY_ENCIPHERMENT" />
			<xs:enumeration value="DATA_ENCIPHERMENT" />
			<xs:enumeration value="KEY_AGREEMENT" />
			<xs:enumeration value="KEY_CERT_SIGN" />
			<xs:enumeration value="CRL_SIGN" />
			<xs:enumeration value="ENCIPHER_ONLY" />
			<xs:enumeration value="DECIPHER_ONLY" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="KeyPurposeId">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ANY_EXTENDED_KEY_USAGE"/>
			<xs:enumeration value="ID_KP_CLIENT_AUTH" />
			<xs:enumeration value="ID_KP_CODE_SIGNING" />
			<xs:enumeration value="ID_KP_EMAIL_PROTECTION" />
			<xs:enumeration value="ID_KP_TIMESTAMPING" />
			<xs:enumeration value="ID_KP_OCSP_SIGNING" />
			<xs:enumeration value="ID_KP_SERVER_AUTH" />
		</xs:restriction>
	</xs:simpleType>
    
   	<xs:simpleType name="ReasonFlag">
		<xs:restriction base="xs:string">
			<xs:enumeration value="UNUSED" />
			<xs:enumeration value="KEY_COMPROMISE" />
			<xs:enumeration value="CA_COMPROMISE" />
			<xs:enumeration value="AFFILIATION_CHANGED" />
			<xs:enumeration value="SUPERSEDED" />
			<xs:enumeration value="CESSATION_OF_OPERATION" />
			<xs:enumeration value="CERTIFICATE_HOLD" />
			<xs:enumeration value="PRIVILEGE_WITHDRAWN" />
			<xs:enumeration value="AA_COMPROMISE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="nonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== consultant-1379/security-poc/pki-web-cli/pki-web-cli-jar/src/test/resources/singleprofile.xml
<Profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ProfilesSchema.xsd">
	
	
	<CertificateProfile Name="RootCA_Cert_Profile">
		<ProfileValidity>2022-05-30</ProfileValidity>
		<ForCAEntity>true</ForCAEntity>
		<Version>V3</Version>
		<SignatureAlgorithm>
			<Name>RSA</Name>
		</SignatureAlgorithm>
		<KeyGenerationAlgorithm>
			<Name>DES</Name>
			<KeySize>1024</KeySize>
		</KeyGenerationAlgorithm>
		<KeyGenerationAlgorithm>
			<Name>DES</Name>
			<KeySize>2048</KeySize>
		</KeyGenerationAlgorithm>
		<CertificateValidity>P2Y</CertificateValidity>
		<SubjectUniqueIdentifier>true</SubjectUniqueIdentifier>
		<IssuerUniqueIdentifier>false</IssuerUniqueIdentifier>
		<SkewCertificateTime>PT50M</SkewCertificateTime>
		<CertificateExtensions>
			<CertificateExtension xsi:type="AuthorityInformationAccess">
				<Critical>false</Critical>
				<AccessDescription>
					<AccessMethod>CA_ISSUER</AccessMethod>
					<AccessLocation>ldap://ldap.example.com/dc=example,dc=com?postalAddress</AccessLocation>
				</AccessDescription>
				<AccessDescription>
					<AccessMethod>OCSP</AccessMethod>
				</AccessDescription>
			</CertificateExtension>
			<CertificateExtension xsi:type="ExtendedKeyUsage">
				<Critical>false</Critical>
				<SupportedKeyPurposeId>ID_KP_EMAIL_PROTECTION</SupportedKeyPurposeId>
				<SupportedKeyPurposeId>ID_KP_TIME_STAMPING</SupportedKeyPurposeId>
			</CertificateExtension>
			<CertificateExtension xsi:type="AuthorityKeyIdentifier">
				<ByKeyIdentifier>true</ByKeyIdentifier>
			</CertificateExtension>
			<CertificateExtension xsi:type="CRLDistributionPoints">
				<Critical>false</Critical>
				<CRLDistributionPoint>
					<DistributionPointName>
						<FullName>ldap://ldap.example.com/cn=exampleCA,dc=example,dc=com?certificateRevocationList;binary</FullName>
					</DistributionPointName>
					<ReasonFlag>CA_COMPROMISE</ReasonFlag>
				</CRLDistributionPoint>
			</CertificateExtension>
			<CertificateExtension xsi:type="BasicConstraints">
				<Critical>true</Critical>
				<Enabled>true</Enabled>
				<IsCA>true</IsCA>
				<PathLenConstraint>3</PathLenConstraint>
			</CertificateExtension>
			<CertificateExtension xsi:type="SubjectKeyIdentifier">
				<Critical>false</Critical>
				<Enabled>true</Enabled>
			</CertificateExtension>
			<CertificateExtension xsi:type="KeyUsage">
				<Critical>true</Critical>
				<SupportedKeyUsageType>CRL_SIGN</SupportedKeyUsageType>
				<SupportedKeyUsageType>KEY_CERT_SIGN</SupportedKeyUsageType>
			</CertificateExtension>
			<CertificateExtension xsi:type="SubjectAltName">
				<Critical>true</Critical>
				<SupportedSubjectAltNameField>DIRECTORY_NAME</SupportedSubjectAltNameField>
				<SupportedSubjectAltNameField>IP_ADDRESS</SupportedSubjectAltNameField>
			</CertificateExtension>
		</CertificateExtensions>
	</CertificateProfile>

</Profiles>

=== consultant-1379/security-poc/pki-web-cli/pki-web-cli-jar/src/test/resources/Certificateprofiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<Profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ProfilesSchema.xsd">
	
	<Certificate-Profiles>
		<CertificateProfile Name="RootCA_Cert_Profile">
			<IsCAEntity>true</IsCAEntity>
			<Version>V3</Version>
			<SignatureAlgorithm>
				<Name>SHA1WITHRSA</Name>
			</SignatureAlgorithm>
			<KeyGenerationAlgorithm>
				<Name>RSA</Name>
				<KeySize>1024</KeySize>
			</KeyGenerationAlgorithm>
			<KeyGenerationAlgorithm>
				<Name>DES</Name>
				<KeySize>2048</KeySize>
			</KeyGenerationAlgorithm>
			<Validity>345d</Validity>
			<SubjectUniqueIdentifier>false</SubjectUniqueIdentifier>
			<IssuerUniqueIdentifier>false</IssuerUniqueIdentifier>
			<SkewCertificateTime>213m</SkewCertificateTime>
			<CertificateExtensions>
			<CertificateExtension xsi:type="SubjectAltName">
				<Critical>true</Critical>
				<SupportedSubjectAltNameField>DIRECTORY_NAME</SupportedSubjectAltNameField>
				<SupportedSubjectAltNameField>IP_ADDRESS</SupportedSubjectAltNameField>
			</CertificateExtension>
			<CertificateExtension xsi:type="KeyUsage">
				<Critical>true</Critical>
				<KeyUsageType>CRL_SIGN</KeyUsageType>
				<KeyUsageType>KEY_AGREEMENT</KeyUsageType>
			</CertificateExtension>
			<CertificateExtension xsi:type="SubjectKeyIdentifier">
				<Critical>false</Critical>
				<Enabled>true</Enabled>
			</CertificateExtension>
			<CertificateExtension xsi:type="ExtendedKeyUsage">
				<Critical>false</Critical>
				<KeyPurposeId>ID_KP_CLIENT_AUTH</KeyPurposeId>
				<KeyPurposeId>ID_KP_CODE_SIGNING</KeyPurposeId>
			</CertificateExtension>
			</CertificateExtensions> 
		</CertificateProfile>
	</Certificate-Profiles>
</Profiles>

=== consultant-1379/security-poc/credential-manager-service/ERICcredentialmanagerservice_CXP9031868/src/main/resources/config/service/data/enmInit/credM/ENM-Root-CA/ENM-Sub1-CA/ENM-END-ENTITIES/Profiles/DEMO_SCEPRA_OAM_CP.xml
<Profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ProfilesSchema.xsd">
  <Certificate-Profiles>
    <CertificateProfile Name="SCEPRA_OAM_CP">
		<SubjectCapabilities>
			<SubjectDN>
				<SubjectEntry>
					<Type>COMMON_NAME</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>SURNAME</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>COUNTRY_NAME</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>LOCALITY_NAME</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>STATE</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>STREET_ADDRESS</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>ORGANIZATION</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>ORGANIZATION_UNIT</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>DN_QUALIFIER</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>TITLE</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>GIVEN_NAME</Type>
				</SubjectEntry>
				<SubjectEntry>
					<Type>SERIAL_NUMBER</Type>
				</SubjectEntry>
			</SubjectDN> 
		</SubjectCapabilities>				
      <IsCAEntity>false</IsCAEntity>
      <Version>V3</Version>
      <SignatureAlgorithm>
        <Name>SHA256withRSA</Name>
        <KeySize>2048</KeySize>
      </SignatureAlgorithm>
      <KeyGenerationAlgorithm>
        <Name>RSA</Name>
        <KeySize>2048</KeySize>
      </KeyGenerationAlgorithm>
      <Validity>P8Y</Validity>
      <Issuer>DEMO_NE_OAM_CA</Issuer>
      <SubjectUniqueIdentifier>false</SubjectUniqueIdentifier>
      <IssuerUniqueIdentifier>false</IssuerUniqueIdentifier>
      <SkewCertificateTime>PT30M</SkewCertificateTime>
      <CertificateExtensions>	
				<CertificateExtension xsi:type="CRLDistributionPoints">
					<Critical>false</Critical>
					<CRLDistributionPoint>
						<DistributionPointName>
							<FullName>http://$FQDN_IPV4/pki-cdps?ca_name=$CANAME&amp;ca_cert_serialnumber=$CACERTSERIALNUMBER</FullName>
						</DistributionPointName>
					</CRLDistributionPoint>
					<CRLDistributionPoint>
						<DistributionPointName>
							<FullName>http://$FQDN_IPV6/pki-cdps?ca_name=$CANAME&amp;ca_cert_serialnumber=$CACERTSERIALNUMBER</FullName>
						</DistributionPointName>
					</CRLDistributionPoint>
					<CRLDistributionPoint>
						<DistributionPointName>
							<FullName>http://$FQDN_DNS/pki-cdps?ca_name=$CANAME&amp;ca_cert_serialnumber=$CACERTSERIALNUMBER</FullName>
						</DistributionPointName>
					</CRLDistributionPoint>					
				</CertificateExtension>

		<CertificateExtension xsi:type="BasicConstraints">
			<Critical>true</Critical>
			<CA>false</CA>
		</CertificateExtension>	 	  
        <CertificateExtension xsi:type="AuthorityKeyIdentifier">
          <Critical>false</Critical>
          <ByAuthorityCertIssuerAndSerialNumber>true</ByAuthorityCertIssuerAndSerialNumber>
        </CertificateExtension>
        <CertificateExtension xsi:type="SubjectKeyIdentifier">
          <Critical>false</Critical>
          <KeyIdentifierAlgorithm>160-BIT_SHA-1</KeyIdentifierAlgorithm>
        </CertificateExtension>
        <CertificateExtension xsi:type="KeyUsage">
          <Critical>true</Critical>
			<KeyUsageType>DIGITAL_SIGNATURE</KeyUsageType>
			<KeyUsageType>KEY_ENCIPHERMENT</KeyUsageType>
			<KeyUsageType>KEY_AGREEMENT</KeyUsageType>
        </CertificateExtension>
      </CertificateExtensions>
    </CertificateProfile>
  </Certificate-Profiles>
</Profiles>

=== consultant-1379/security-poc/pki-web-cli/pki-web-cli-jar/src/test/resources/Entityprofiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<Profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ProfilesSchema.xsd">
<Entity-Profiles>
		<EntityProfile Name="RootCA_Entity_Profile">
			<Subject>
				<SubjectDN>
					<SubjectEntry>
						<Type>COMMON_NAME</Type>
						<Value>ARJ_ROOT_CA</Value>
					</SubjectEntry>
				</SubjectDN>
			</Subject>
			<SubjectAltNameValues>
				<SubjectAltNameValue>
					<Type>DIRECTORY_NAME</Type>
					<Value xsi:type="SubjectAltNameString">
						<StringValue>Email = arj@ar.com</StringValue>
					</Value>
				</SubjectAltNameValue>
				<SubjectAltNameValue>
					<Type>OTHER_NAME</Type>
					<Value xsi:type="OtherName">
						<TypeId>12.2.2.2</TypeId>
						<Value>SrSr</Value>
					</Value>
				</SubjectAltNameValue>
			</SubjectAltNameValues>
			<KeyGenerationAlgorithm>
				<Name>DES</Name>
				<KeySize>2048</KeySize>
			</KeyGenerationAlgorithm>
			<CertificateProfileName>RootCA_Cert_Profile</CertificateProfileName>
			
			<CertificateExtensions>
			<CertificateExtension xsi:type="KeyUsage">
			<Critical>true</Critical>
				<KeyUsageType>CRL_SIGN</KeyUsageType>
			</CertificateExtension>
			<CertificateExtension xsi:type="ExtendedKeyUsage">
				<Critical>false</Critical>
				<KeyPurposeId>ID_KP_CLIENT_AUTH</KeyPurposeId>
			</CertificateExtension>
			</CertificateExtensions>
		</EntityProfile>
	</Entity-Profiles>
</Profiles>

=== consultant-1379/security-poc/credential-manager-service/ERICcredentialmanagerservice_CXP9031868/src/main/resources/config/service/data/enmInit/credM/ENM-Root-CA/ENM-Sub1-CA/ENM-END-ENTITIES/Profiles/DEMO_SCEPRA_IPsec_EP.xml
<?xml version="1.0" encoding="utf-8"?>
<Profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ProfilesSchema.xsd">
  <Entity-Profiles>
    <EntityProfile Name="SCEPRA_IPSec_EP">
      <Subject>
        <SubjectDN>
          <SubjectEntry>
            <Type>COMMON_NAME</Type>
            <Value>?</Value>
          </SubjectEntry>
          <SubjectEntry>
            <Type>ORGANIZATION_UNIT</Type>
            <Value>BUCI_DUAC_NAM</Value>
          </SubjectEntry>
          <SubjectEntry>
            <Type>ORGANIZATION</Type>
            <Value>ERICSSON</Value>
          </SubjectEntry>
          <SubjectEntry>
            <Type>COUNTRY_NAME</Type>
            <Value>SE</Value>
          </SubjectEntry>
        </SubjectDN>
      </Subject>
      <KeyGenerationAlgorithm>
        <Name>RSA</Name>
        <KeySize>2048</KeySize>
      </KeyGenerationAlgorithm>
      <CertificateProfileName>SCEPRA_IPsec_CP</CertificateProfileName>
      <TrustProfileName>IPSEC_NE_CHAIN_TP</TrustProfileName>
      <CertificateExtensions>
        <CertificateExtension xsi:type="KeyUsage">
          <Critical>true</Critical>
			<KeyUsageType>DIGITAL_SIGNATURE</KeyUsageType>
			<KeyUsageType>KEY_ENCIPHERMENT</KeyUsageType>
			<KeyUsageType>KEY_AGREEMENT</KeyUsageType>
        </CertificateExtension>
      </CertificateExtensions>
    </EntityProfile>
  </Entity-Profiles>
</Profiles>
