=== consultant-1379/security-poc/pki-manager/pki-credentialsmanagement-jar/src/main/resources/pkimanagercredentialsrequest.xsd
<xs:schema attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="applications" type="ApplicationsType" />
	
	<xs:complexType name="ApplicationsType">
		<xs:sequence>
			<xs:element name="application" type="ApplicationType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ApplicationType">
		<xs:sequence>
			<xs:element name="certificates" type="CertificatesType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="CertificatesType">
		<xs:sequence>
			<xs:element name="certificate" type="CertificateType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
 
    <xs:complexType name="CertificateType">
		<xs:sequence>
			<xs:element name="overlapperiod" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="tbscertificate" type="TBSCertificateType" minOccurs="1" maxOccurs="1" />
			<xs:element name="endentityprofilename" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="keypair" type="KeypairType" minOccurs="1" maxOccurs="1" />
			<xs:element name="keystore"  type="KeyStoreType" minOccurs="1" maxOccurs="unbounded" />
			<xs:element name="truststore" type="TrustStoreType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="StoreType">
		<xs:sequence>
			<xs:element name="storealias" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="storelocation" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="storepassword" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="KeyStoreType">
		<xs:choice>
			<xs:element name="pkcs12keystore" type="StoreType" minOccurs="1" maxOccurs="1" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="TrustStoreType">
        <xs:sequence>
			<xs:element name="jkstruststore" type="StoreType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TBSCertificateType">
		<xs:sequence>
			<xs:element name="subject" type="SubjectType" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SubjectType">
		<xs:sequence>
			<xs:element name="entityname" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="distinguishname" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="KeypairType">
		<xs:sequence>
			<xs:element name="keypairsize" type="xs:positiveInteger" minOccurs="1" maxOccurs="1" />
			<xs:element name="keypairalgorithm" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== consultant-1379/security-poc/pki-manager/ERICpkimanager_CXP9031873/src/main/resources/pkimanagercredentialsrequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="pkimanagercredentialsrequest.xsd">
	<application>
		<certificates>
<!--Credentials for Secure communication -->	
			<certificate>
				 <overlapperiod>P2D</overlapperiod>
				<tbscertificate>
					<subject>
						<entityname>##HOSTNAME##_Infrastructure_PKI_Manager</entityname>
						<distinguishname>CN=##HOSTNAME##_Infrastructure_PKI_Manager, O=ericsson, OU=enm, C=SE</distinguishname>
					</subject>
				</tbscertificate>
				<endentityprofilename>credMServiceProfile</endentityprofilename>
				<keypair>
					<keypairsize>2048</keypairsize>
					<keypairalgorithm>RSA</keypairalgorithm>
				</keypair>
				<keystore>
					<pkcs12keystore>
						<storealias>infrastructure_pki_manager</storealias>
						<storelocation>/ericsson/sps/data/certs/PKIManagerKeyStore.p12</storelocation>
						<storepassword>C4bCzXyT</storepassword>
					</pkcs12keystore>
				</keystore>
				<truststore>
						<jkstruststore>
							<storealias>infrastructure_pki_manager_trust</storealias>
							<storelocation>/ericsson/sps/data/certs/PKIManagerTrustStore.jks</storelocation>
							<storepassword>C4bCzXyT</storepassword>
						</jkstruststore>
				</truststore>
			</certificate>			
		</certificates>
	</application>
</applications>
