=== consultant-1379/security-poc/credentialmanagercli/credentialmanagercli-xmlbeans/src/main/resources/CertificateRequest.xsd
<xs:schema attributeFormDefault="unqualified"

	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Root element to support multiple applications -->
	<xs:element name="applications" type="ApplicationsType" />

	<xs:complexType name="ApplicationsType">

		<xs:sequence>
			<xs:element name="application" type="ApplicationType"
				minOccurs="1" maxOccurs="unbounded" />

			<xs:element name="user" type="UserType" 
				minOccurs="1" maxOccurs="1" />

		</xs:sequence>

	</xs:complexType>


	<!-- Application element to hold certificate information about an individual 
		application -->
	<xs:complexType name="ApplicationType">

		<xs:sequence>
			<xs:element name="certificates" type="CertificatesType"
				minOccurs="0" maxOccurs="1" />
				
			<xs:element name="truststores" type="TrustStoresOnlyType"
				minOccurs="0" maxOccurs="1" />	

			<xs:element name="crlupdatemode" type="CrlUpdateModeType" 
				minOccurs="1" maxOccurs="1" />

			<xs:element name="keyrequests" type="KeyRequestsType"
				minOccurs="0" maxOccurs="1" />

		</xs:sequence>

	</xs:complexType>


	<!-- Support generating multiple certificates for single application -->
	<xs:complexType name="CertificatesType">

		<xs:sequence>
			<xs:element name="certificate" type="CertificateType"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>

	</xs:complexType>


	<!-- Certificate, keystore and truststore information -->
	<xs:complexType name="CertificateType">

		<xs:sequence>
			<xs:element name="certificatechain" type="xs:boolean"
             minOccurs="0" default="false"/>
		
			<xs:element name="tbscertificate" type="TBSCertificateType"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="endentityprofilename" type="xs:string"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="keypair" type="KeypairType" 
				minOccurs="0" maxOccurs="1" />
			<xs:element name="keystore"  type="KeyStoreType" 
				minOccurs="1" maxOccurs="unbounded" />
			<xs:element name="truststore" type="TrustStoreType"
				minOccurs="0" maxOccurs="unbounded" />

			<xs:element name="crlstore" type="CrlStoreType"  
				minOccurs="0" maxOccurs="unbounded" />

			<xs:element name="postscript" type="CommandType"
				minOccurs="0" maxOccurs="1" />

			<xs:element name="oncheckresult" type="CheckActionListType"
				minOccurs="0" maxOccurs="1" />

		</xs:sequence>

	</xs:complexType>
	
	
	<xs:complexType name="TrustStoresOnlyType">

		<xs:sequence>
			<xs:element name="truststoreonly" type="TrustStoreOnlyType"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>

	</xs:complexType>
	
	
	<!-- truststore for client that don't need a certificate -->
	<xs:complexType name="TrustStoreOnlyType">

		<xs:sequence>
		
			<xs:element name="trustprofilename" type="xs:string"
				minOccurs="1" maxOccurs="1" />		
	
			<xs:element name="truststore" type="TrustStoreType"
				minOccurs="1" maxOccurs="unbounded" />

			<xs:element name="crlstore" type="CrlStoreType"  
				minOccurs="0" maxOccurs="unbounded" />
				
			<xs:element name="postscript" type="CommandType"
				minOccurs="0" maxOccurs="1" />

			<xs:element name="oncheckresult" type="CheckActionListType"
				minOccurs="0" maxOccurs="1" />
				
		</xs:sequence>

	</xs:complexType>
	


<!-- how the service retrieves the CRL update -->
	<xs:simpleType name="CrlUpdateModeType"  >

   	 	<xs:restriction base="xs:string">
        		<xs:enumeration value="CrlSelfManaged" />
        		<xs:enumeration value="CrlRequired" />
      		 <xs:enumeration value="CrlNotManaged" />
    	</xs:restriction>

	</xs:simpleType>


	<!-- Support generating keys for single application -->
	<xs:complexType name="KeyRequestsType">
		<xs:sequence>

			<xs:element name="secretkeyrequest" type="SecretKeyRequestType" 
				minOccurs="0" maxOccurs="unbounded" />

			<xs:element name="keypairrequest" type="KeyPairRequestType" 
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>


<!-- parameters to define a symmetric key -->
	<xs:complexType name="SecretKeyRequestType">

		<xs:sequence>
			<!-- Key size -->
			<xs:element name="keysize" type="xs:positiveInteger" 
 				minOccurs="1" maxOccurs="1" />

			<!-- Key pair algorithm like DES -->
			<xs:element name="keyalgorithm" type="xs:string" 
				minOccurs="1" maxOccurs="1" />

			<xs:element name="keystore" type="SecretStoreType"  
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>


<!-- parameters to define a pair of keys (public private) -->
	<xs:complexType name="KeyPairRequestType">
		<xs:sequence>
			<!-- Key size -->
			<xs:element name="keysize" type="xs:positiveInteger" 
 				minOccurs="1" maxOccurs="1" />

			<!-- Key pair algorithm like RSA -->
			<xs:element name="keyalgorithm" type="xs:string" 
				minOccurs="1" maxOccurs="1" />

			<xs:element name="keystore" type="KeyPairStoreType"  
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="KeyStoreType">
		<xs:choice>
			<xs:element name="jcekskeystore" type="KStoreType"  />
			<xs:element name="jkskeystore" type="KStoreType"  />
			<xs:element name="pkcs12keystore" type="KStoreType"  />
			<xs:element name="base64keystore" type="Base64KStoreType"  />
		</xs:choice>
	</xs:complexType>


	<xs:complexType name="KStoreType">
		<xs:sequence>
			<xs:element name="storealias" type="xs:string" 
				minOccurs="1" maxOccurs="1" />
			<xs:element name="storelocation" type="xs:string"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="storepassword" type="xs:string" 
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="Base64KStoreType">
        <xs:sequence>
			<xs:element name="storealias" type="xs:string" 
				minOccurs="1" maxOccurs="1" />
			<xs:choice>

		        <xs:sequence>
					<xs:element name="keyfilelocation" type="xs:string" 
						minOccurs="1" maxOccurs="1" />
					<xs:element name="certificatefilelocation" type="xs:string" 
						minOccurs="0" maxOccurs="1" />
		        </xs:sequence>

       			<xs:element type="xs:string" name="storelocation" />
			</xs:choice>

			<xs:element type="xs:string" name="storepassword"
				minOccurs="0" maxOccurs="1" />
        </xs:sequence>
	</xs:complexType>


	<xs:complexType name="TrustStoreType">
        <xs:sequence>
			<xs:element name="trustsource" type="TrustSourceType" 
				minOccurs="0" maxOccurs="1" default="both"/>
		<xs:choice>
			<xs:element name="jcekstruststore" type="TStoreType" />
			<xs:element name="jkstruststore" type="TStoreType" />
			<xs:element name="pkcs12truststore" type="TStoreType" />
			<xs:element name="base64truststore" type="Base64TStoreType"  />
		</xs:choice>
        </xs:sequence>
	</xs:complexType>

	<xs:simpleType name="TrustSourceType"  >
	    <xs:restriction base="xs:string">
	        <xs:enumeration value="internal" />
	        <xs:enumeration value="external" />
	        <xs:enumeration value="both" />
	    </xs:restriction>
	</xs:simpleType>


	<xs:complexType name="TStoreType">
		<xs:sequence>
			<xs:element name="storealias" type="xs:string" 
				minOccurs="1" maxOccurs="1" />

			<xs:choice>
				<xs:element name="storelocation" type="xs:string" />
				<xs:element name="storefolder" type="xs:string"  />
			</xs:choice>

			<xs:element name="storepassword" type="xs:string" 
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="Base64TStoreType">
        <xs:sequence>
			<xs:element name="storealias" type="xs:string" 
				minOccurs="1" maxOccurs="1" />
			<xs:choice>
       			<xs:element type="xs:string" name="storelocation" />
       			<xs:element type="xs:string" name="storefolder" />
			</xs:choice>

			<xs:element type="xs:string" name="storepassword"
				minOccurs="0" maxOccurs="1" />
        </xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="SecretStoreType">

		<xs:choice>
			<xs:element name="jcekssecretstore" type="KStoreType"  />
			<xs:element name="pkcs12secretstore" type="KStoreType"  />
			<xs:element name="base64secretstore" type="Base64KStoreType" />
		</xs:choice>

	</xs:complexType>


	<xs:complexType name="KeyPairStoreType">

		<xs:choice>
			<xs:element name="jcekskeypairstore" type="KStoreType"  />
			<xs:element name="jkskeypairstore" type="KStoreType"  />
			<xs:element name="pkcs12keypairstore" type="KStoreType"  />
			<xs:element name="base64keypairstore" type="Base64KStoreType" />
		</xs:choice>

	</xs:complexType>


	<xs:complexType name="CrlStoreType">
	   <xs:sequence>
		<xs:element name="crlsource" type="CrlSourceType" 
				minOccurs="0" maxOccurs="1" default="both"/>

		<xs:choice>
			<xs:element name="base64crlstore" type="Base64TStoreType" />
		</xs:choice>
		</xs:sequence>
	</xs:complexType>


	<xs:simpleType name="CrlSourceType"  >
	    <xs:restriction base="xs:string">
	        <xs:enumeration value="internal" />
	        <xs:enumeration value="external" />
	        <xs:enumeration value="both" />
	    </xs:restriction>
	</xs:simpleType>


	<xs:complexType name="TBSCertificateType">

		<xs:sequence>
			<!-- Certificate Subject -->
			<xs:element name="subject" type="SubjectType" 
				minOccurs="1" maxOccurs="1" />
			<!-- Certificate Extensions -->
			<xs:element name="certificateextension" type="CertificateExtensionType"
				minOccurs="0" maxOccurs="1" />

		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="SubjectType">
		<xs:sequence>
			<xs:element name="entityname" type="xs:string"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="distinguishname" type="xs:string"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="CertificateExtensionType">
		<xs:sequence>
			<xs:element name="subjectalternativename" type="SubjectAlternativeNameType"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="SubjectAlternativeNameType">
		<xs:sequence>
			<xs:element name="directoryname" minOccurs="0" maxOccurs="unbounded"
				type="xs:string" />
			<xs:element name="dns" minOccurs="0" maxOccurs="unbounded"
				type="xs:string" />
			<xs:element name="email" minOccurs="0" maxOccurs="unbounded"
				type="xs:string" />
			<xs:element name="uri" minOccurs="0" maxOccurs="unbounded"
				type="xs:string" />
			<xs:element name="ipaddress" minOccurs="0" maxOccurs="unbounded"
				type="xs:string" />
			<xs:element name="othername" minOccurs="0" maxOccurs="unbounded"
				type="xs:string" />
			<xs:element name="registeredid" minOccurs="0" maxOccurs="unbounded"
				type="xs:string" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="KeypairType">
		<xs:sequence>
			<!-- Key pair size -->
			<xs:element name="keypairsize" type="xs:positiveInteger" 
				minOccurs="1" maxOccurs="1" />

			<!-- Key pair algorithm like RSA -->
			<xs:element name="keypairalgorithm" type="xs:string" 
				minOccurs="1" maxOccurs="1" />

		</xs:sequence>
	</xs:complexType>


<!-- On check actions management start -->

	<xs:simpleType name="ActionCauseType">
	    <xs:restriction base="xs:string">
	        <xs:enumeration value="certificateUpdate"/>
	        <xs:enumeration value="trustUpdate"/>
	        <xs:enumeration value="crlUpdate"/>
	    </xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ActionType">
	    <xs:restriction base="xs:string">
	        <xs:enumeration value="VMRestart"/>
	        <xs:enumeration value="HTTPSConnectorRestart"/>
	        <xs:enumeration value="RunScript"/>
	    </xs:restriction>
	</xs:simpleType>		

	<xs:complexType name="ParameterType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="value" type="xs:string"/> 
		</xs:sequence>
	</xs:complexType>		
	
	<xs:complexType name="CommandType">
		<xs:sequence>
			<xs:element name="pathname" type="xs:string" 
				minOccurs="1" maxOccurs="unbounded"/>		
			<xs:element name="parameter" type="ParameterType" 
				minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>		

	<xs:complexType name="CheckActionType">
		<xs:sequence>
			<!-- List of action cause -->
			<xs:element name="checkcause" type="ActionCauseType" 
				minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="action" type="ActionType"/>
			<!-- Script to call -->
			<xs:element name="command" type="CommandType"
				minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CheckActionListType">
		<xs:sequence>
			<xs:element name="actionlist" type="CheckActionType" 
				minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

<!-- On check actions management end -->


<!-- TO BE REMOVED

<xs:simpleType name="ConnectorManagedType"  >

    <xs:restriction base="xs:string">
        <xs:enumeration value="httpsConnector" />
        <xs:enumeration value="undefined" />
    </xs:restriction>
</xs:simpleType>
-->

	<xs:complexType name="UserType">

		<xs:sequence>
<!-- keep in the same line to allow grep researches -->
			<xs:element name="username" type="xs:string" 
				minOccurs="1" maxOccurs="1" />

<!-- keep in the same line to allow grep researches -->
			<xs:element name="usergroup" type="xs:string" 
				minOccurs="1" maxOccurs="1" />
		</xs:sequence>

	</xs:complexType>


</xs:schema>

=== consultant-1379/security-poc/eric-enm-charts/eric-enm-stateless-integration/charts/eric-enmsg-mskpirt/appconfig/certificatesdata/NeConn_CertRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../RemoteSystemsTempFiles/CertificateRequest.xsd">
  <application>
    <certificates>
      <certificate>
        <certificatechain>true</certificatechain>
        <tbscertificate>
          <subject>
            <entityname>NetworkElementConnector##hostname##</entityname>
            <distinguishname>CN=NetworkElementConnector_##hostname##</distinguishname>
          </subject>
        </tbscertificate>
        <endentityprofilename>ENM_System_SBI_TPFC_EP</endentityprofilename>
        <keystore>
          <pkcs12keystore>
            <storealias>server-cert</storealias>
            <storelocation>/ericsson/neconn/data/certs/cert.p12</storelocation>            
            <storepassword>secmgmt</storepassword>
          </pkcs12keystore>
        </keystore>
        <truststore>
          <base64truststore>
            <storealias>trustca</storealias>
	    <storelocation>/ericsson/neconn/data/certs/trustca_all.pem</storelocation>
            <storepassword>secmgmt</storepassword>
          </base64truststore>
        </truststore>
        <oncheckresult>
          <actionlist>
            <checkcause>certificateUpdate</checkcause>
            <checkcause>trustUpdate</checkcause>
            <action>VMRestart</action>
          </actionlist>
        </oncheckresult>
      </certificate>
    </certificates>
    <crlupdatemode>CrlRequired</crlupdatemode>
  </application>
  <user>
    <username>jboss_user</username>
    <usergroup>jboss</usergroup>
  </user>
</applications>

=== consultant-1379/security-poc/credentialmanagercli/credentialmanagercli-jar/src/test/resources/validXMLActionJKS.xml
<?xml version="1.0" encoding="UTF-8"?>
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="CertificateRequest.xsd">
	<application>
		<certificates>
			<certificate>
			
				<tbscertificate>
					<subject>
						<!--  <entityname>atclvm387##HOSTNAME##</entityname> -->
						<entityname>atclvm387##HOSTNAME##</entityname>
						<distinguishname>CN=##HOSTNAME##_atclvm387, O=ericsson, OU=enm, C=SE</distinguishname>
					</subject>
				</tbscertificate>
				
				<endentityprofilename>CMPRA_EP</endentityprofilename>
				
				<keystore>
					<jkskeystore>
						<storealias>teste</storealias >
						<storelocation>certs/TestAction.JKS</storelocation>
						<storepassword></storepassword>
					</jkskeystore>
				</keystore>

				<truststore>
					<jkstruststore>
						<storealias>TestCA1</storealias >
						<storelocation>certs/TestTSAction.JKS</storelocation>
						<storepassword></storepassword>
					</jkstruststore>
				</truststore>								
				
				<oncheckresult>
                     <actionlist>
                            <checkcause>certificateUpdate</checkcause>
                            <checkcause>trustUpdate</checkcause>
                            <action>RunScript</action>
                                 <command>
                                       <pathname>helloworld.sh</pathname>
                                       <parameter>
                                            <name>port</name>
                                             <value>1024</value>
                                       </parameter>
                                 </command>
                      </actionlist>      
                </oncheckresult>			
				<!-- <connectormanaged>httpsConnector</connectormanaged> -->

			</certificate>
		</certificates>
		
			<crlupdatemode>CrlSelfManaged</crlupdatemode>
			
		<keyrequests>
		
			<secretkeyrequest>
				<keysize>64</keysize>
				<keyalgorithm>DES</keyalgorithm>
				<keystore>
					<jcekssecretstore>
						<storealias>secretalias</storealias>
						<storelocation>keystore.p12</storelocation>
						<storepassword>changeit</storepassword>
					</jcekssecretstore>
				</keystore>	
			</secretkeyrequest>
			
			<keypairrequest>
				<keysize>64</keysize>
				<keyalgorithm>DES</keyalgorithm>
				<keystore>
					<jkskeypairstore>
						<storealias>secretalias</storealias>
						<storelocation>keystore.p12</storelocation>
						<storepassword>changeit</storepassword>
					</jkskeypairstore>
				</keystore>		
			</keypairrequest>
			
		</keyrequests>
			
			
	</application>
	<user>
		<!-- keep in the same line to allow grep researches -->
		<username>myUser</username>
		<usergroup>myGroup</usergroup>
	</user>
</applications>

=== consultant-1379/security-poc/eric-enm-charts/eric-enm-stateless-integration/charts/eric-enmsg-mspm/appconfig/certificatesdata/NETCONF_ENM_MEDIATION_Base64.xml
<?xml version="1.0" encoding="UTF-8"?>
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CertificateRequest.xsd">
  <application>
    <certificates>
      <certificate>
        <certificatechain>true</certificatechain>
        <tbscertificate>
          <subject>
            <entityname>##hostname##_ENM_NETCONF_MEDIATION</entityname>
          </subject>
	</tbscertificate>
	<endentityprofilename>ENM_System_SBI_COM_TPFC_EK_EP</endentityprofilename>
	<keypair>
	  <keypairsize>2048</keypairsize>
	  <keypairalgorithm>RSA</keypairalgorithm>
	</keypair>
	<keystore>
	  <base64keystore>
	    <storealias>NETCONF_ENM_MEDIATION_KEYSTORE</storealias>
	    <keyfilelocation>/ericsson/mediation/data/certs/tlsnetconf.key</keyfilelocation>
	    <certificatefilelocation>/ericsson/mediation/data/certs/tlsnetconf.cert</certificatefilelocation>
	  </base64keystore>
	</keystore>
	<keystore>
	  <jkskeystore>
	    <storealias>NETCONF_ENM_MEDIATION_KEYSTORE</storealias>
	    <storelocation>/ericsson/mediation/data/certs/tlshttpsconf.jks</storelocation>
	    <storepassword>secret</storepassword>
	  </jkskeystore>
	</keystore>
	<truststore>
	  <base64truststore>
	    <storealias>NETCONF_ENM_MEDIATION_TRUSTSTORE</storealias>
	    <storelocation>/ericsson/mediation/data/certs/tlsnetconfCA.pem</storelocation>
          </base64truststore>
	</truststore>
	<truststore>
	  <jkstruststore>
	    <storealias>NETCONF_ENM_MEDIATION_TRUSTSTORE</storealias>
	    <storelocation>/ericsson/mediation/data/certs/tlshttpsconfCA.jks</storelocation>
	    <storepassword>secret</storepassword>
          </jkstruststore>
	</truststore>
      </certificate>
    </certificates>
    <crlupdatemode>CrlNotManaged</crlupdatemode>
  </application>
  <user>
    <username>root</username>
    <usergroup>root</usergroup>
  </user>
</applications>

=== consultant-1379/security-poc/credentialmanagercli/credentialmanagercli-jar/src/test/resources/CheckValidXMLPKCS12.xml
<?xml version="1.0" encoding="UTF-8"?>
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="CertificateRequest.xsd">
	<application>
		<certificates>
			<certificate>
				<tbscertificate>
					<subject>
						<distinguishname>CN=atclvm387</distinguishname>
					</subject>
					<certificateextension>
						<subjectalternativename>
							<ipaddress>1.1.1.1</ipaddress>
						</subjectalternativename>
					</certificateextension>
				</tbscertificate>
				
				<endentityprofilename>TOREndEntityProfile</endentityprofilename>
				
				<keypair>
					<keypairsize>2048</keypairsize>
					<keypairalgorithm>RSA</keypairalgorithm>
				</keypair>
		
				<keystore>
					<pkcs12keystore>
						<storealias>keystore</storealias >
						<storelocation>keystore.p12</storelocation>
						<storepassword>changeit</storepassword>
					</pkcs12keystore>
				</keystore>

				<truststore>
					<pkcs12truststore>
						<storealias>TestCA1</storealias >
						<storelocation>keystore.p12</storelocation>
						<storepassword>changeit</storepassword>
					</pkcs12truststore>
				</truststore>
								
				<!-- <connectormanaged>httpsConnector</connectormanaged> -->
				
			</certificate>
		</certificates>
		
			<crlupdatemode>CrlSelfManaged</crlupdatemode>
			
		<keyrequests>
		
			<secretkeyrequest>
				<keysize>64</keysize>
				<keyalgorithm>DES</keyalgorithm>
				<keystore>
					<pkcs12secretstore>
						<storealias>secretalias</storealias>
						<storelocation>keystore.p12</storelocation>
						<storepassword>changeit</storepassword>
					</pkcs12secretstore>
				</keystore>	
			</secretkeyrequest>
			
			<keypairrequest>
				<keysize>64</keysize>
				<keyalgorithm>DES</keyalgorithm>
				<keystore>
					<pkcs12keypairstore>
						<storealias>secretalias</storealias>
						<storelocation>keystore.p12</storelocation>
						<storepassword>changeit</storepassword>
					</pkcs12keypairstore>
				</keystore>		
			</keypairrequest>
			
		</keyrequests>
			
	</application>
	
	<user>
		<!-- keep in the same line to allow grep researches -->
		<username>myUser</username>
		<usergroup>myGroup</usergroup>
	</user>

</applications>

=== consultant-1379/security-poc/eric-enm-charts/eric-enm-stateless-integration/charts/eric-enmsg-identity-mgmt-service/appconfig/certificatesdata/FIDM-ExtIdp_CertRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CertificateRequest.xsd">
	<application>
		<truststores>
			<truststoreonly>
			 <trustprofilename>IdP_NBI_TP</trustprofilename>
				<truststore>
					<jkstruststore>
						<storealias>federated-identity-mgmt-service-extidpts</storealias>
						<storelocation>/opt/ericsson/com.ericsson.oss.services.security.identitymgmt.federated-identity-mgmgt-service/truststore</storelocation>
						<storepassword>passw0rd</storepassword>
					</jkstruststore>
				</truststore>
				<oncheckresult>
					<actionlist>
						<checkcause>trustUpdate</checkcause>
						<action>VMRestart</action>
					</actionlist>
				</oncheckresult>
			</truststoreonly>
		</truststores>
		<crlupdatemode>CrlNotManaged</crlupdatemode>
	</application>
	<user>
		<!-- keep in the same line to allow grep researches -->
		<username>root</username>
		<usergroup>root</usergroup>
	</user>
</applications>

=== consultant-1379/security-poc/eric-enm-charts/eric-enm-stateless-integration/charts/eric-enmsg-remotedesktop/appconfig/certificatesdata/tlwebaccess_CertRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CertificateRequest.xsd">
    <application>
        <certificates>
            <certificate>
                <certificatechain>true</certificatechain>
                <tbscertificate>
                    <subject>
                        <entityname>##hostname##_TLWEBACCESS_SERVER</entityname>
                        <distinguishname>CN=##hostname##</distinguishname>
                    </subject>
                </tbscertificate>
                <endentityprofilename>ENM_System_SBI_TPFC_EP</endentityprofilename>
                <keystore>
                    <base64keystore>
                        <storealias>tlwebaccess</storealias>
                        <keyfilelocation>/opt/thinlinc/etc/tlwebaccess/server.key</keyfilelocation>
                        <certificatefilelocation>/opt/thinlinc/etc/tlwebaccess/server.crt</certificatefilelocation>
                    </base64keystore>
                </keystore>
                <postscript>
                    <pathname>/ericsson/ERICcendiothinlinc_CXP9031953/scripts/control_thinlinc_services.sh</pathname>
                </postscript>
                <oncheckresult>
                    <actionlist>
                        <checkcause>certificateUpdate</checkcause>
                        <checkcause>trustUpdate</checkcause>
                        <action>RunScript</action>
                        <command>
                            <pathname>/ericsson/ERICcendiothinlinc_CXP9031953/scripts/control_thinlinc_services.sh</pathname>
                        </command>
                    </actionlist>
                </oncheckresult>
            </certificate>
        </certificates>
        <crlupdatemode>CrlRequired</crlupdatemode>
    </application>
    <user>
        <username>root</username>
        <usergroup>root</usergroup>
    </user>
</applications>

=== consultant-1379/security-poc/eric-enm-charts/eric-enm-stateless-integration/charts/eric-enmsg-fm-history/appconfig/certificatesdata/FM_EMAIL_DIGITAL_SIGNATURE.xml
<?xml version="1.0" encoding="UTF-8"?>
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="CertificateRequest.xsd">
    <application>
        <certificates>
            <certificate>
                <tbscertificate>
                    <subject>
                        <entityname>##HOSTNAME##</entityname>
                        <distinguishname>CN=##HOSTNAME##, O=ericsson, OU=enm, C=SE</distinguishname>
                    </subject>
                    <!--now certificateextension not present: default SubjectAlternativeName 
 (profile) is used -->
                </tbscertificate>
                <!-- Alarm_Monitor_Client_Email_EP profile must defined/configured on 
 PKI -->
                <!-- Alarm_Monitor_Client_Email_EP is hard coded on CredM Service -->
                <!-- CLI and JBoss use the same profile -->
                <endentityprofilename>Alarm_Monitor_Client_Email_EP</endentityprofilename>
                <keypair>
                    <keypairsize>2048</keypairsize>
                    <keypairalgorithm>RSA</keypairalgorithm>
                </keypair>
                <keystore>
                    <jkskeystore>
                        <!--please refer also to jboss standalone.xml -->
                        <storealias>jbossVault</storealias>
                        <storelocation>/ericsson/fm/data/certs/FM_EMAIL_DIGITAL_SIGNATURE.jks</storelocation>
                        <storepassword>jbossKS</storepassword>
                    </jkskeystore>
                </keystore>
            </certificate>
        </certificates>
        <crlupdatemode>CrlRequired</crlupdatemode>
    </application>
    
    <user>
        <username>jboss_user</username>
        <usergroup>jboss</usergroup>
    </user>
    
</applications>
